// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Rn_dnfD31X_N4TnwWqS8--7KwoL02sc',
    appId: '1:565279805914:android:3ed1cdf7cd8919d08830e3',
    messagingSenderId: '565279805914',
    projectId: 'flutterfirebase-59b46',
    storageBucket: 'flutterfirebase-59b46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQs88B5qEY6ULUKxWMkbXed1Wpoms84bI',
    appId: '1:565279805914:ios:99c2b0cbf5d36fc48830e3',
    messagingSenderId: '565279805914',
    projectId: 'flutterfirebase-59b46',
    storageBucket: 'flutterfirebase-59b46.appspot.com',
    iosClientId: '565279805914-khtotanjqggks5vq0inbor9aol7ga19j.apps.googleusercontent.com',
    iosBundleId: 'com.limitlessflutter.app',
  );
}
